name: Build
on:
  pull_request:
    # Build all pull requests, regardless of what their base branch is.
    branches: [ '**' ]
    types:
      # Default types (see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request)
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

# Automatically cancel previous runs for the same ref (i.e. branch) and event type. The latter component prevents
# manually dispatched events (i.e. manual actions) from being cancelled by pushes to the main branch.
concurrency:
  group: ${{ github.ref }}-${{ github.event_name }}-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 18
    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 1000000

      - name: Build
        env:
          VITE_CLIENT_ID: ${{ secrets.VITE_CLIENT_ID }}
          VITE_CLIENT_SECRET: ${{ secrets.VITE_CLIENT_SECRET }}
          VITE_REDIRECT_URI: ${{ secrets.VITE_REDIRECT_URI }}

        run: yarn make
