name: Dynamic Tests
on:
  pull_request:
    # Build all pull requests, regardless of what their base branch is.
    branches: [ '**' ]
    types:
      # Default types (see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request)
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

# Automatically cancel previous runs for the same ref (i.e. branch) and event type. The latter component prevents
# manually dispatched events (i.e. manual actions) from being cancelled by pushes to the main branch.
concurrency:
  group: ${{ github.ref }}-${{ github.event_name }}-dynamic-tests
  cancel-in-progress: true

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run ProjectCanvas unit tests
        run: yarn test

  e2e:
    timeout-minutes: 60
    name: E2E Tests
    runs-on: ubuntu-latest
    env:
      VITE_CLIENT_ID: ${{ secrets.VITE_CLIENT_ID }}
      VITE_CLIENT_SECRET: ${{ secrets.VITE_CLIENT_SECRET }}
      VITE_REDIRECT_URI: ${{ secrets.VITE_REDIRECT_URI }}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - run: npx playwright install --with-deps chromium

      - name: Run e2e tests
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- yarn e2e

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30

      - name: Upload Playwright screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-screenshots
          path: e2e/screenshots
          retention-days: 30
